services:
  pihole:
    container_name: pihole
    image: pihole/pihole:dev
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8080:80/tcp"
    environment:
      TZ: 'Europe/Oslo'
      WEBPASSWORD: ${WEBPASSWORD}
      PIHOLE_DNS_: 1.1.1.1;8.8.8.8
      WEBTHEME: default-dark
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
