services:
  pihole:
    container_name: pihole
    image: pihole/pihole:dev
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8080:80/tcp"
    environment:
      TZ: 'Europe/Oslo'
      WEBPASSWORD: ${WEBPASSWORD}
      PIHOLE_DNS_: 1.1.1.1;8.8.8.8
      WEBTHEME: default-dark
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  metabase:
    container_name: metabase
    image: bobblybook/metabase:latest
    ports:
      - "3000:3000"
    environment:
      JAVA_TIMEZONE: 'Europe/Oslo'
      MB_DB_TYPE: mysql
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 3306
      MB_DB_USER: ${METABASEDBUSER}
      MB_DB_PASS: ${METABASEDBPASS}
      MB_DB_HOST: host.docker.internal
      MB_DB_CONNECTION_URI: "jdbc:mysql://host.docker.internal:3306/metabase?user=${METABASEDBUSER}&password=${METABASEDBPASS}"

    volumes:
      - './metabase-data:/metabase-data'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped


  busybox:
    image: busybox
    container_name: busybox
    command: sh -c "echo 'Hello from BusyBox!' && sleep infinity"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      MB_DB_USER: ${METABASEDBUSER}
      MB_DB_PASS: ${METABASEDBPASS}

  dovecot:
    image: dovecot/core:latest  # Use the official Dovecot Docker image
    container_name: dovecot
    restart: always
    volumes:
      - ./dovecot/config:/etc/dovecot  # Mount your custom configuration
      - ./dovecot/mail:/var/mail         # Store emails persistently
      - ./logs:/var/log/dovecot   # log to host

    ports:
      - 143:143                  # IMAP
      - 993:993                  # IMAPS
    # Add other ports (POP3, etc.) if needed